In [3]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [30]:
env = gym.make("FrozenLake-v1", render_mode='human')

In [5]:
action_space_size= env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
#print(q_table)

In [6]:
num_episodes = 10000
max_steps_per_episode = 1000

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate =1
min_exploration_rate = 0.01
exploration_decay_rate = 0.0008

In [7]:
reward_all_episodes = []

# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()[0]
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        #Exploration vs exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold> exploration_rate :
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, truncated, info = env.step(action)
        
        
        #update the Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1- learning_rate) +\
        learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True or truncated == True:
            break
    
    #exploration rate decay
    exploration_rate = min_exploration_rate +(max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    reward_all_episodes.append(rewards_current_episode)
                             
#calculate the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(reward_all_episodes),num_episodes/1000)
count =1000
print("******Average reward per thousand episodes*******\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

#print updated Q-table
print("\n\n*******Q-table*******")
print(q_table)

/home/aimkeys/.local/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


******Average reward per thousand episodes*******

1000 :  0.035000000000000024
2000 :  0.1520000000000001
3000 :  0.31900000000000023
4000 :  0.43700000000000033
5000 :  0.5790000000000004
6000 :  0.6320000000000005
7000 :  0.6820000000000005
8000 :  0.6580000000000005
9000 :  0.6650000000000005
10000 :  0.6820000000000005


*******Q-table*******
[[0.55807959 0.50789425 0.51042785 0.50477195]
 [0.395009   0.26671524 0.36454637 0.50053091]
 [0.41817287 0.37852804 0.41142538 0.4737756 ]
 [0.26642018 0.30051188 0.32089859 0.4626277 ]
 [0.57780768 0.42419327 0.29902106 0.32470129]
 [0.         0.         0.         0.        ]
 [0.35943409 0.16322996 0.14795894 0.15340924]
 [0.         0.         0.         0.        ]
 [0.48647666 0.51596785 0.41120541 0.60067476]
 [0.37086089 0.63681017 0.42064335 0.46508011]
 [0.57110969 0.33525167 0.40159673 0.30924477]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.45449672 0.35794957 0.75517543 0.63

In [31]:
for episode in range(3):
    s = env.reset()
    state = s[0]
    done = False
    
    print("\n\n\n*******Episode", episode+1, "*******\n")
    time.sleep(0.4)
    env.render()
    
    for step in range(max_steps_per_episode):
#         clear_output(wait=True)
#         env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state, :])

        result = env.step(action)
        new_state, reward, done, truncated, info = result
        
        if done:
            print(reward)
            if reward == 1:
                print("***Cool stuff! You win!***")
            else:
                print("***Damn, you fell!***")
            time.sleep(3)
            break
                
        state = new_state
        
env.close()




*******Episode 1 *******

0.0
***Damn, you fell!***



*******Episode 2 *******

0.0
***Damn, you fell!***



*******Episode 3 *******

1.0
***Cool stuff! You win!***


In [15]:
np.argmax(q_table[1,:])
q_table

array([[0.55807959, 0.50789425, 0.51042785, 0.50477195],
       [0.395009  , 0.26671524, 0.36454637, 0.50053091],
       [0.41817287, 0.37852804, 0.41142538, 0.4737756 ],
       [0.26642018, 0.30051188, 0.32089859, 0.4626277 ],
       [0.57780768, 0.42419327, 0.29902106, 0.32470129],
       [0.        , 0.        , 0.        , 0.        ],
       [0.35943409, 0.16322996, 0.14795894, 0.15340924],
       [0.        , 0.        , 0.        , 0.        ],
       [0.48647666, 0.51596785, 0.41120541, 0.60067476],
       [0.37086089, 0.63681017, 0.42064335, 0.46508011],
       [0.57110969, 0.33525167, 0.40159673, 0.30924477],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.45449672, 0.35794957, 0.75517543, 0.63237435],
       [0.73074649, 0.89863976, 0.77268884, 0.76272043],
       [0.        , 0.        , 0.        , 0.        ]])

In [ ]:
env.close()